### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by 0xpierson** [sogko/go-wordpress#1]
Thank you for your contribution. It's useful to me. But It's not working. When I create a Post, It return 400 bad request. I think you missing "Content-Type": "application/json" param for headers.

**Comment by ndinhphi** [comment]
Thank you for your contribution. It's useful to me. But It's not working. When I create a Post, It return 400 bad request. I think you missing "Content-Type": "application/json" param for headers.

**Comment by sogko** [comment]
Hi @ndinhphi 
Thanks for taking your time out to try `go-wordpress`, appreciate it very much 👍🏻

I'll look into this, but could you kindly share some information about your Wordpress setup, for e.g.:
- Wordpress version
- [WP-API plugin](http://v2.wp-api.org) version 
- [WP-API's BasicAuth plugin](https://github.com/WP-API/Basic-Auth) version

Thanks!

**Comment by 0xpierson** [comment]
Hi @sogko 
Wordpress version:  4.4.2
WP-API: 2.0-beta12
WP-API BasicAuth: Version 0.1

Thank you so much!

**Comment by sogko** [comment]
Hi @ndinhphi 

I've pushed some changes that should address the issue with not being able to update/create a Post.
(The new WP-API plugin seems to particular about nil/empty fields)

Could you give the new changes a try and see if it helps?

Regarding the unit tests failing, there are a lot of breaking changes with the new version of WP-API.
I'll address those in another issue / PR.

**Comment by 0xpierson** [comment]
Hi @sogko . It works fine to me now :+1: 
Thank you from the bottom of my heart for everything!

**Comment by sogko** [comment]
Hi @ndinhphi 
Glad to hear that it helped! 

Cheers!
